// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmTpe1cHbfCQOlaXHEgONFwi6FFYJ_HFU',
    appId: '1:446570003033:web:164bc658a3a7f920634f48',
    messagingSenderId: '446570003033',
    projectId: 'foto-paylasim-app-a6d08',
    authDomain: 'foto-paylasim-app-a6d08.firebaseapp.com',
    storageBucket: 'foto-paylasim-app-a6d08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnWdOqWW5dC1RAgAZ5GkJXVenAuqPI8wI',
    appId: '1:446570003033:android:2fa375a97674a32f634f48',
    messagingSenderId: '446570003033',
    projectId: 'foto-paylasim-app-a6d08',
    storageBucket: 'foto-paylasim-app-a6d08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCilGOP1szzyw8AB1h897KSI0bNqWQlc3Q',
    appId: '1:446570003033:ios:ff9c056fcaeefa6d634f48',
    messagingSenderId: '446570003033',
    projectId: 'foto-paylasim-app-a6d08',
    storageBucket: 'foto-paylasim-app-a6d08.appspot.com',
    iosClientId: '446570003033-s687n72hruff0sjbkaretv1o6tsm64lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fotopaylasimapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCilGOP1szzyw8AB1h897KSI0bNqWQlc3Q',
    appId: '1:446570003033:ios:ff9c056fcaeefa6d634f48',
    messagingSenderId: '446570003033',
    projectId: 'foto-paylasim-app-a6d08',
    storageBucket: 'foto-paylasim-app-a6d08.appspot.com',
    iosClientId: '446570003033-s687n72hruff0sjbkaretv1o6tsm64lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fotopaylasimapp',
  );
}
