class Yazilar {
  String tarihi =
      "Edirnenin en eski halkı, Traklar soyundan Odrisler'in yörede, Meriç ve Tunca ırmaklarının birleştiği bugünkü Edirne'nin bulunduğu yerde bir kent kurdukları bilinmektedir. Odrisler'den sonra yöreye egemen olan Makedonyalılar Dönemi'nde kent, büyük bir olasılıkla Odris yada Odrisia adının değişmesi sonucu, Orestia/Orestas olarak anılmaya başlanmıştır. \n İS II. yy' da Roma İmparatoru Hadrianus, (117-138) Orestia Kasabası'nın stratejik önemi nedeniyle buraya kent statüsü verdi ve kendi adını koydu. Böylece, Roma Dönemi'nde kent Hadrianopolis/Hadrianupolis/Adrianupolis/Adrianapolis adlarıyla anıldı. Adrianopolis zamanla Adrianople/Adrianopel olarak değişti. \n Osmanlı dönemi başlarında Edrinus/Edrune/Edrinabolu/Endriye diye anıldı. 1476'da yazılan Aşıkpaşazade Tarihi'nde kentin adı Edrene olarak geçer. XVI.yy başlarında kentin Edirne olarak adlandırıldığı görülür. Edirne 1361 yılında I.Murat tarafından fethedilmiş ve İstanbul'un alınışına kadar 88 yıl(1365-1453) boyunca Osmanlı Devleti'nin başkenti olmuştur. \n Tarihinde çeşitli unvanları hak etmiştir. Edirne, mutluluk dönemlerinde Der-i Saadet (Mutluluk Kapısı) bir Şenlikler Şehri dır. II. Murad'dan IV. Mehmet'e kadar zafer kutlamaları, sünnet şenlikleri, II.Mehmet'in evlilik törenleri İstanbul'u kıskandıracak kadar' olurdu. Edirne tabii ki her dönemde hatırlarda bir 'Der-i Saadet' olarak kalmadı. Bu 'Serhat Şehri' Evliya Çelebi'nin sözleriyle 'Bir İslam Duvan' tarihinde birçok kez felaketle de tanıştı. En fazlada kuşatma ve işgallerden bunaldı. Şenlikleriyle 'Mutluluk Kapısı' olarak hatırlanan Edirne'nin yanına 'Daima bağrı yanık olan Edirne'yi de koymak gerekir. \n Edirne her zaman kültür olaylarının yoğun yaşandığı bir kent olmuştur. Mimari yenilikler bu kentin yapılarıyla gelmiş; hat ve süsleme sanatının en güzel örnekleri burada verilmiş, çok sayıda medresesi yoğun tartışmalara tanık olmuş, tıp tarihine geçen ilk uygulamalar burda başlamıştır.\n Kimliğini asıl Osmanlı döneminde bulan ve imparatorluğun ikinci kenti olan Edirne, kültürel mirasımızın en yoğun hissedildiği bir kenttir. \n Edime, camileri, çarşıları, köprüleri, tarihi evleriyle ve özellikle de Muhteşem Selimiye ile ülkemize gelenleri ilk karşılayan ve bir sınır kenti olma özelliğini en iyi yansıtan kentimizdir.";


  String yer1 ="1. Enez Kalesi\nYüksek bir tepe üzerinde yer alan Enez Kalesi’nin yapım yılı tam olarak bilinmese de duvarlarında kullanılan yapı malzemeleri yapının Bizans dönemi öncesinde yapıldığına işaret ediyor. Tarihçi Prokopios’e göre Balkanlardan gelen tehlikeleri önlemek amacıyla yapılan kalenin, bazı kaynaklara göre MS. VI. yüzyılda Iustinianus tarafından onarıldığı söyleniyor. Edirne’nin Keşan’a bağlı sahil bölgesi Enez’de yer alan yapıyı, Edirne ziyaretinize ekleyeceğiniz bir Enez kaçışı sırasında görebilirsiniz.";

  String yer2 ="2. Hıdırlık Tabyası\nBalkan Harbi sırasında Edirne’nin savunması için önemli bir rol oynayan Hıdırlık Tabyası da Edirne’de görmeniz gereken yerlerden biri. Edirne Müdafii Şükrü Paşa’nın karargahı olan tabya, yakın tarih meraklıları tarafından büyük ilgi görüyor.";

  String yer3 ="3. Rüstem Paşa Kervansarayı\nEdirne merkezinde yer alan Rüstempaşa Kervansarayı, Osmanlı mimarisinin en önemli örneklerinden biri. Rüstempaşa tarafından Osmanlı mimarisinin ustası Mimar Sinan’a yaptırılan kervansarayın içerisinde, dikdörtgen avlular çevresinde 2 katlı odalar bulunuyor. Revaklı avlularıyla dikkat çeken yapı, 1972 yılında renove edilerek otel olarak hizmet vermeye başlıyor. 1980 yılında Ağa Han Mimarlık Ödülü’nü alan Kervansaray, ulaşıma da elverişli konumu ile Edirne’de görülecek yerler listesine mutlaka eklenmeli!";

  String yer4 ="4. Sweti George Bulgar Kilisesi\nEdirne’nin Kıyık mevkiinde yer alan Sweti George Bulgar Kilisesi’nin 1880 yılında yaptırıldığı biliniyor. Daha önce burada bulunan bir kilisenin bazı tablolarına ev sahipliği yapan kilise, halk arasında Bulgar Kilisesi olarak biliniyor. Günümüzde de ibadete açık olan kilise, sabah 10.00 itibariyle ziyarete açılıyor.";

  String yer5 ="5. Meriç Köprüsü\nAbdülmecit tarafından yaptırılan Meriç (Mecidiye) Köprüsü; Edirne-Karağaç yolunda Meriç Nehri üzerinde yer alıyor. 263 metre uzunluğundaki köprünün, 13 ayak üzerinde 12 sivri kemeri bulunuyor. Ortasında mermerden bir yazıt köşkü olan köprü, Edirne’nin sembollerinden biri olmasının yanı sıra Osmanlı Dönemi’ne ait en güzel köprü örneklerinden de biri.";

  String yer6 = "6. Selimiye Camii\nOsmanlı mimarisinin en güzel eserlerinden biri olan Selimiye Camii, Edirne’de görmeniz gereken yerlerin başında geliyor. II. Selim’in Mimar Sinan’a yaptırdığı caminin yapımına, 1568 yılında başlandığı biliniyor. Mimar Sinan’ın “ustalık eserim” dediği cami, 8 dayanaklı cami planının da en başarılı örneği. Mimarisiyle olduğu kadar taş, mermer, çini ve ahşap sedef gibi süsleme sanatlarıyla da ziyaretçilerini büyüleyen caminin geniş dış avlusunda; Darül-Sübyan, Darül-Kur’a ve Darül-Hadis yapıları bulunuyor.";

  String yemek1 ="Mutancana\nKuru kayısı, kuru üzüm, kuru erik ve kırmızı et ile hazırlanan mutancana, Osmanlı'dan miras kalmıştır. Edirne mutfağına özgü bir yemek olan mutancana, genellikle kuzu veya geyik eti ile hazırlanır.";
  String yemek2 = "Bulgur Çorbası\nAna malzemesi bulgur ve salça olan bu çorba, kış aylarında şifa kaynağı olarak tüketilir.";
  String yemek3 = "Edirne Tava Ciğeri\nEdirne'nin en meşhur ve en lezzetli yemeği şüphesiz ki ciğer tavadır. Ciğer sevmeyenleri bile kendine hayran bırakan bu yemek, şehre gelen turistlerinde ilgisini çekiyor.";
  String yemek4 =  "Edirne Köftesi\nEdirne de ciğer satılan restoranlarda mutlaka köfteye de yer verilir. Sebze ve kıymalı harç ile hazırlanan Edirne köftesi de, yoğun ilgi gören yemekler arasındadır.";
  String yemek5 =  "Kuzu Etli Elbasan Tava\nKöklü bir geçmişe sahip olan elbasan tava, genellikle kuzu eti ile hazırlanır. Arnavut mutfağıyla özdeşleşse de, ülkemizde en güzel elbasan tavalar Edirne mutfağında hazırlanmaktadır.";

}
